/**
 * PROTOTYPE — throwaway, wayfinder ticket #82.
 *
 * The fixture hand is generated by the *real* engine, not hand-written: a
 * scripted command stream is piped through `decide`/`apply` exactly as the
 * harness does, and the emitted events are the replay's event log. That
 * matters for a transport prototype — the beat structure under test
 * (especially the auto-cascading street transitions from issue #9, which
 * arrive as several events from a single `decide` call) is the engine's real
 * one, not an approximation of it.
 */
import {
  apply,
  createInitialState,
  decide,
  legalActions,
} from "@table-top-poker/protocol";
import type {
  ActionType,
  Command,
  EngineState,
  HandEvent,
  SeatId,
} from "@table-top-poker/protocol";

export const fixtureSeatIds: readonly SeatId[] = [0, 1, 2, 3, 4, 5];

/**
 * Applies one command, folding every emitted event into state and appending
 * it to the log. A `Rejection` is a non-event here: the prototype's script is
 * legal by construction, and rejections never reach a player-facing replay
 * anyway (map #79).
 */
function step(
  state: EngineState,
  command: Command,
  log: HandEvent[],
): EngineState {
  const result = decide(state, command);
  if (!Array.isArray(result)) {
    throw new Error(`prototype script produced a rejection: ${result.reason}`);
  }
  let next = state;
  for (const event of result) {
    next = apply(next, event);
    log.push(event);
  }
  return next;
}

/** The seat currently owed a decision, or null once the hand is complete. */
function actorOf(state: EngineState): SeatId | null {
  return state.hand?.status === "betting"
    ? (state.hand.toAct[0] ?? null)
    : null;
}

/**
 * Drives the hand with a script of intents, one per decision in turn order.
 * Each intent is checked against the engine's own `legalActions` and swapped
 * for its counterpart when illegal (`check` ↔ `call`), so the script survives
 * the engine's real turn order — the big-blind option, the requeue after a
 * raise — without having to encode any of it.
 */
function driveHand(
  state: EngineState,
  script: readonly ActionType[],
  log: HandEvent[],
): EngineState {
  let current = state;
  let i = 0;
  // Bounded so a script that never closes the hand fails loudly rather than
  // hanging the browser tab.
  for (let guard = 0; guard < 200; guard++) {
    const actor = actorOf(current);
    if (actor === null) return current;

    const hand = current.hand;
    if (hand?.status !== "betting") return current;
    const legal = legalActions(hand, actor);

    let intent: ActionType = script[i] ?? "check";
    i += 1;
    if (!legal.includes(intent)) {
      intent =
        intent === "check" ? "call" : intent === "call" ? "check" : "fold";
    }

    current = step(current, { type: intent, playerId: actor }, log);
  }
  throw new Error("prototype script did not complete the hand");
}

export interface FixtureHand {
  readonly handNumber: number;
  readonly events: readonly HandEvent[];
  readonly initial: EngineState;
}

/**
 * The hand under test, chosen to exercise every beat class the transport has
 * to pace: a deal, early folds, three board deals, a flop raise war that
 * requeues the street, and a showdown. Deliberately a *long* hand — a short
 * one flatters autoplay and hides how stepping scales.
 */
function buildFixtureHand(): FixtureHand {
  const initial = createInitialState([...fixtureSeatIds]);
  const log: HandEvent[] = [];

  const started = step(
    initial,
    { type: "startHand", playerId: 0, seed: "replay-transport-82" },
    log,
  );

  driveHand(
    started,
    [
      // Preflop: two fold out early, the rest see a flop.
      "fold",
      "fold",
      "call",
      "call",
      "call",
      "check",
      // Flop: checked to a raise, one folds, two come along.
      "check",
      "check",
      "raise",
      "fold",
      "call",
      "call",
      // Turn: a second raise, one more gone.
      "check",
      "raise",
      "call",
      "fold",
      // River: checked down to showdown.
      "check",
      "check",
    ],
    log,
  );

  return { handNumber: 12, events: log, initial };
}

export const fixtureHand: FixtureHand = buildFixtureHand();

/** Position `n` is the state after applying `n` events — map #79's ordinal. */
export function stateAt(hand: FixtureHand, position: number): EngineState {
  const clamped = Math.max(0, Math.min(position, hand.events.length));
  let state = hand.initial;
  for (const event of hand.events.slice(0, clamped)) {
    state = apply(state, event);
  }
  return state;
}
